server:
  port: 8090


stripe_api_key: sk_test_EJqVAJuWv4zDOfnhLLtSCUdhffffggggggggg7777   #stripe apikey







spring:
  servlet:
    multipart:
      max-file-size: 10Mb  #设置单个文件的大小
      max-request-size: 100Mb #设置单次请求的文件的总大小
  redis:
    host: 172.16.1.48   #redis服务器地址
    port: 6379            #连接端口
    database: 0           #redis数据库索引
    timeout: 10000      #连接超时时间
    jedis:
      pool:
        max-active: 8    #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8    # 连接池中的最大空闲连接
        min-idle: 0   # 连接池中的最小空闲连接
  messages:
    basename: i18n/messages
    cache-duration: 3600
    fallback-to-system-locale: true

  #配置日志
logging:
  level:
    com.highrock:  debug
  path: /usr/log/72demo
  config: classpath:logback-spring.xml




